# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e7f2f6b85348c8f9cd50e8c45806f0088b36f000239d6390b5fb44275dc5f69009fb1e9cbae7c5613421ee6c54ecc018f415ed4957916adadbb50766cf09ea

test:
  secret_key_base: 48207b22640d11578d01e818eeaa791f4f57d61a0ad5c0a002c618987d5b70e9b92c6aa062f35821bcdebc36e6b7c8a56ea7f1f88853f3c50e753984d3d64638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
